{{- if .Values.rbac.create -}}
{{- if .Values.rbac.clusterWide }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "sre-bot.fullname" . }}
  labels:
    {{- include "sre-bot.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "sre-bot.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "sre-bot.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "sre-bot.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sre-bot.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "sre-bot.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "sre-bot.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
